name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: BrowserStack Action
        uses: 'browserstack/github-actions@master'
        with:
          username:  ${{ secrets.BROWSERSTACK_USERNAME }}
          access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          build-name: github-actions-test
          project-name: bstack-demo
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npx cypress run
          browser: chrome